name: Pull request site preview
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/jekyll-build-pages@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Deploy via GoStatic
        id: deploy
        uses: DigitalSVN/GoStatic@v1.0
        with:
          api-token: ${{ secrets.GOSTATIC_API_TOKEN }}
          source-dir: './_site'
      - name: Output the deployment URL
        run: echo "URL ${{ steps.deploy.outputs.url }}"
      - name: Comment Pull Request
        uses: thollander/actions-comment-pull-request@v2.3.1
        with:
          message: |
            'URL ready:  ${{ steps.deploy.outputs.url }}'
