name: Pull request site preview
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      pull-requests: write 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/jekyll-build-pages@v1
      - name: Deploy via GoStatic
        id: deploy
        uses: DigitalSVN/GoStatic@v1.1
        with:
          api-token: ${{ secrets.GOSTATIC_API_TOKEN }}
          source-dir: './_site'
      - name: Output the deployment URL
        run: echo "URL ${{ steps.deploy.outputs.url }}"
      - name: Comment Pull Request
        uses: thollander/actions-comment-pull-request@v2.4.0
        with:
          comment_tag: site-preview
          reactions: rocket
          message: |
            URL ready at ${{ steps.deploy.outputs.url }}!
